# Indeed Auto-Apply Bot Configuration
# Edit these fields to customize your job search and application process


search:
  base_url: "https://ie.indeed.com/jobs?q=&l=Dublin%2C+County+Dublin&radius=10&sc=0kf%3Aattr%2875GKK%29%3B&from=searchOnDesktopSerp&vjk=afa2e0f9b7fce51e"

  start: 0
  end: 100 # default is 100, you can set it to 1000 or more for larger searches (not recommanded though)

camoufox:
  user_data_dir: "user_data_dir"
  language: "uk" # uk, us, fr, de, es, it, nl, pt, pl, ro, tr, ru, cn etc...





